name: ASSD
channels:
  - pytorch
  - nvidia
  - conda-forge
  - pyg
  - bioconda
dependencies:
  - python=3.8
  - pytorch::pytorch==1.12.0
  - pytorch::torchvision==0.13.0
  - pytorch::torchaudio==0.12.0
  - cudatoolkit=11.3
  - ca-certificates
  - openssl
  - pyg::pyg
  - pyg::pytorch-scatter
  - pyg::pytorch-sparse
  - pyg::pytorch-cluster
  - pyg::pytorch-spline-conv
  - certifi
  - torchdata
  - torchtext
  - biotite
  - loralib
  - mmseqs2
  - bioconda::hmmer
